### ISSUE TITLE
Add in for Firefox android not available 

### ISSUE THREAD

**Issue by n9u5** [SauceLLC/sauce4strava#138]
Hi, love sauce!

I am trying to install sauce for Firefox on my android tablet via https://addons.mozilla.org/en-US/android/addon/sauce4strava/ however the option to install is blocked and the subtext reads as follows 'To find add-ons compatible with Firefox for Android, click here. Just wondering if this is an issue on my end or if it's Mozilla playing games.

Cheers

**Comment by mayfield** [comment]
Hi @n9u5,

Unfortunately this is on Mozilla.  They've decided to indefinitely pause support for general add-ons for mobile Firefox.  They have an extremely short list of "recommended" add-ons that they hand picked based on global usage, which will never qualify a boutique extension like Sauce IMO.

They claimed it was temporary at first but it's been around 2 years now, so I've given up hope.  A real shame because it runs just fine actually.  But in order to even test it you have to jump through some extreme hoops on the Nightly build of Firefox.
