### ISSUE TITLE
enhancement request: weekly TSS in training log?

### ISSUE THREAD

**Issue by tannenba** [SauceLLC/sauce4strava#16]
Just installed Sauce on Firefox, very nice job!!!!

One feature I've dreamed about: in the "Training Log" page, by default Strava shows Total Relative Effort for each week.  Strava gives options to see other weekly totals, such as miles, but has no option to show weekly "Training Load" or (obviously) TSS.

It would be wonderful to see weekly TSS totals.  Or even Strava's tss substitute of 'Training Load', if that is easier.  For activities that do not have power data, I think it would be fine to count them as zero TSS.

**Comment by mayfield** [comment]
Hi Todd,

Thanks for writing in with the suggestion.  The current release doesn't
store all your activity data so unless Strava provides an API for getting
this sort of information on the fly I can't do much, and they don't provide
a simple way to get training load data like this without inspecting each
and every activity.  TSS for example is calculated by using the raw data
streams.

BUT...

The next major release IS going to feature a synchronization engine that
will allow Sauce to do exactly this sort of thing.  I've long wanted to
avoid storing any user data on my own servers for privacy and cost reasons,
so I've avoided doing a sync engine of any kind.  Also Strava is
notorious for punting their official API users, so I've been reluctant to
invest in that path.   But recently I decided it would be worth looking
into a model that doesn't use their official APIs but instead just
downloads the raw data in the browser itself and stores them in the
browsers database (IndexedDB).   As the developer I never have access to
your data and it never leaves your computer.  Additionally I don't have to
pay for expensive server hosting since every user is basically acting as
their own server.

With this in place, computing and storing TSS and tTSS (also coming in the
next release for non-power activities) will be trivial and I can show that
data in all the existing strava locations as well as build an entirely new
Sauce based training page.  I'll also be able to show and compare your peak
power (and NP, pace, HR, etc) from a single activity with all your
historical records.  Think a personal leaderboard for your peak
performances with your past performances, either over all time or
periodized by season, so you can see how your spring training is going
compared to prior years for example.  There are going to be no shortages of
things I can do with this engine in place.

Cheers!
Justin

**Comment by mayfield** [comment]
![image](https://user-images.githubusercontent.com/139316/103181535-2e407000-485f-11eb-9f0f-97af124470e1.png)

Here's s sneak peak at what I'm able to do so far.  I'm building up the `SyncManager` code to handle keeping all your activities imported while staying within Strava's throttling limits.

**Comment by mayfield** [comment]
Going to close this cause I can't modify the Training Log page now that's been rewritten in React.  :(
