### ISSUE TITLE
Firefox add on is not compatible with Firefox for Android

### ISSUE THREAD

**Issue by mobusby** [SauceLLC/sauce4strava#164]
The add on does not appear to be compatible with Firefox for Android, anymore.

![SmartSelect_20230725_155511_Firefox](https://github.com/SauceLLC/sauce4strava/assets/7889558/c7c63b54-678a-4f20-ac38-d823dd3c3d75)

Using latest Firefox from Google Play store, Samsung Galaxy Tab S6 and Galaxy S21 Ultra.

**Comment by mayfield** [comment]
Sadly this is because Firefox ended support for 99.9% of mobile extensions when they switched to the "Quantum" code base (any version after 68).  They claimed that they would eventually bring support back but they never did (and never will IMO).  The only extensions they allow are a small list of "recommended" extensions that have mass market appeal like ad-blockers.

I recommend Kiwi Browser for extension support on Android.  It's chromium based, so you'll want to use the chrome web store for installing sauce.

**Comment by mobusby** [comment]
Thanks. Disappointing that Mozilla went that way. I'll give Kiwi a shot.

**Comment by mayfield** [comment]
> Thanks. Disappointing that Mozilla went that way. I'll give Kiwi a shot.

I agree, especially since it works perfectly if you can install it (requires a developer build and cmd line tools).  The restriction is completely non-technical.
