### ISSUE TITLE
Use Fitness Tracking and Peak Performances on mobile (iOS device)

### ISSUE THREAD

**Issue by alexcolo** [SauceLLC/sauce4strava#169]
Hello, is there a way for using above functionalities on iOS devices? I tried with both Safari and Chrome (on iPhone and iPad) and I cannot see them.

**Comment by mayfield** [comment]
Unfortunately no.  The Safari engine has a broken database implementation
that is required for the fitness tracking system to work properly, so it's
disabled on that browser.  And iOS is crippled to only use the Safari
engine (even if you install something like Chrome on there, the engine is
still Safari because of Apple policies).

If you have an Android device there are some more options, but that's
probably not very helpful. :/

Justin
