### ISSUE TITLE
Support Activity Timestamp Parsing

### ISSUE THREAD

**Issue by Ilink** [SauceLLC/sauce4strava#214]
Non-owned activities don't have their timestamps parsed correctly, which makes exports a little tricky. After reading the source, I noticed this was because it requires scraping the page itself. I think this wouldn't be too terribly difficult to do, especially with the aid of something like https://github.com/wanasit/chrono. This library also supports a few different languages. I would be more than happy to implement this feature, but I don't want to do it if you're opposed due to the maintenence overhead, or some other reason. Thank you!

**Comment by mayfield** [comment]
Hi @Ilink,

I'm definitely reluctant to bring in a new dep unless it's really earth shattering.  Every dep has to be bundled locally and it can't be minified or obfuscated in anyway to adhere with the various store submission guidelines.  Well, it's a bit more complicated than that but I currently submit my package as a "full source included" style package that makes the store submission process much easier and reliable.  I also see in the README that `de` and `zh` are only partially supported by that lib which are unfortunately large portions of the user base.

That being said I think the proposition of getting a timestamp in the analysis view for all activities has gotten even worse since I wrote that code.  Many activities won't even feature a timestamp in localized form now.  I think it's related to a users privacy settings but I've not done a deep dive on it.  

For example...
![image](https://github.com/user-attachments/assets/ea4a00bf-847f-4bf1-8e13-b62aeb546efb)

There is a source for reliable timestamps but it requires the athlete being synchronized with the Sauce Performance system.  I'd definitely accept a change to the `analysis.js::exportActivity()` func that looked for a timestamp within the Sauce database for synchronized athletes.  I.e. added a check for `ns.syncActivity.ts` to the timestamp lookup process.  Failing that, I also wouldn't argue against a UI dialog that simply asks for you to put the date in using a `input[type="datetime-local"]` picker.

**Comment by Ilink** [comment]
Thanks for the detailed explanation @mayfield! I figured the language support wasn't quite good enough in that package. Although it also seems that's sort of a moot point considering the timestamps change granularity so drastically like you've shown here. 

I can start with implementing a UI element that provides a date, I think that sounds like a good low-maintenance solution.

**Comment by mayfield** [comment]
That looks good to me.

I'm curious about the TZ change though.  Can you point me to what you're doing?

**Comment by Ilink** [comment]
Here's the PR https://github.com/SauceLLC/sauce4strava/pull/216
