### ISSUE TITLE
 Sync job error: TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by reldridge83** [SauceLLC/sauce4strava#218]
Getting the following error when trying to run Sauce Activity Sync using Edge. Any ideas? Not been able to use Fitness Tracking since 24 October 2024. Sauce seems to work fine using Chrome
[sauce-sync-10797963.log](https://github.com/user-attachments/files/17722436/sauce-sync-10797963.log)

**Comment by mayfield** [comment]
Hi @reldridge83 what version of sauce do you have installed?  Can you check that it's updated via chrome://extentions -> en Developer Mode -> Update?

**Comment by reldridge83** [comment]
Its using Edge - 8.4.3 (7f663578bc)

**Comment by mayfield** [comment]
I assume the update process didn't promote passed 8.4.3 because you're installed from the Microsoft store instead of the Google one.  I've since unlisted that store because MS is not really supporting it and it takes weeks to update.

Can you uninstall the MS based install and then reinstall from here:

https://chromewebstore.google.com/detail/sauce-for-strava/eigiefcapdcdmncdghkeahgfmnobigha

You'll get the latest version and be on the update track for the latest code as soon as I can publish it.

**Comment by reldridge83** [comment]
Thanks - that seems to have done the trick!

**Comment by YetAnotherDickwall** [comment]
Thanks Same problem for me. I looked it up here and very quickly resolved. 
Frankly mate you are brilliant!

Tempted to wonder how one guy can deliver software that is beautiful, works and does the job when teams can struggle to deliver stuff that works badly. Thanks.
